<?php

namespace AppBundle\Repository;

/**
 * NpiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NpiRepository extends \Doctrine\ORM\EntityRepository
{
}
