<?php

namespace AppBundle\Repository;

/**
 * ProductIngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductIngredientRepository extends \Doctrine\ORM\EntityRepository
{
}
